version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: geoserver-postgis
    environment:
      POSTGRES_DB: geoserver
      POSTGRES_USER: geoserver
      POSTGRES_PASSWORD: geoserver
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geoserver"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - geoserver-network

  geoserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geoserver
    environment:
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DB: geoserver
      POSTGRES_USER: geoserver
      POSTGRES_PASSWORD: geoserver
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8080:8080"
    depends_on:
      postgis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - geoserver-network

volumes:
  postgis-data:
  geoserver-data:

networks:
  geoserver-network:
    driver: bridge
